root_dir : /media/aolab/untitiled/workspace/PlastSurg
batch_size : 1  
gpus : [0]
out_features : 6
num_workers : 16
save_top_k : 1
early_stopping_metric : val_acc_phase
feature_output_path : /media/aolab/untitiled/workspace/PlastSurg/outputs
mstcn_output_path : /media/aolab/untitiled/workspace/PlastSurg/outputs_tecno
log_every_n_steps : 1
mstcn_causal_conv : True
mstcn_learning_rate : 0.001
mstcn_min_epochs : 12
mstcn_max_epochs : 16
mstcn_layers : 8
mstcn_f_maps : 32
mstcn_f_dim: 2054
mstcn_stages : 2
mstcn_early_stopping_metric : val_acc
name : sample